steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/sehatyuk-api/sehat-yuk-api"
      - "."
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/sehatyuk-api/sehat-yuk-api"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "beta"
      - "run"
      - "services"
      - "add-iam-policy-binding"
      - "sehat-yuk-api"
      - "--region=asia-southeast2"
      - "--member=allUsers"
      - "--role=roles/run.invoker"
options:
  logging: CLOUD_LOGGING_ONLY